<a href="https://colab.research.google.com/github/Anmolkr1909/Numpy/blob/main/Numpy_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy ( Mini project )**

---



---



 # 94) Student Marks Analyzer
*   Analyze marks of students in 5 subjects
*   Used in schools, college results, dashboards
#  Topic used :

*  ndarray creation

* Indexing & slicing

*  Axis-based operations (mean, max, std)

*  Comparison

*  Boolean filtering

#  Problem Statement:
*  You have marks of 4 students in 5 subjects.
# Analyze:

* Each student's average

* Each subject's highest scorer

*  Students who scored more than 50 in all subjects



In [4]:
import numpy as np

#Create 2D array: rows = students, cols = subjects
marks = np.array([
    [78, 55, 62, 85, 90],   # Student 1
    [92, 88, 95, 91, 87],   # Student 2
    [45, 60, 52, 22, 65],   # Student 3
    [80, 70, 60, 55, 75]    # Student 4])
]) # Added closing parenthesis and adjusted indentation

# Student-wise average marks (axis=1)
student_avg = np.mean(marks, axis=1)
print("Average marks per student:", student_avg)

# Subject-wise topper (axis=0)
subject_topper = np.argmax(marks, axis=0)
print("Index of toppers per subject:", subject_topper)

# Find students who scored >50 in ALL subjects
passed_all = np.all(marks > 50, axis=1)
print("Students who passed all subjects:", passed_all)

# Print marks of students who passed all subjects
passed_students = marks[passed_all]
print("Marks of students who passed all:", passed_students)

Average marks per student: [74.  90.6 48.8 68. ]
Index of toppers per subject: [1 1 1 1 0]
Students who passed all subjects: [ True  True False  True]
Marks of students who passed all: [[78 55 62 85 90]
 [92 88 95 91 87]
 [80 70 60 55 75]]




---



 #  95) Weather Data Processor
*  Analyze daily temperatures of a city for a week using NumPy
* Weather apps, climate dashboards, agriculture tool
# Topics:

*   Min, Max, Mean, Std

*  Axis-based stats

*  Conditional selection

*  np.where(), np.any(), np.all()

# Problem Statement:
*  You have temperature readings (°C) of a city over 7 days, taken at 3 times per day: Morning, Afternoon, and Evening.

# Need to:

* Find the hottest and coldest day

* Get average temperature of each day

* Detect heatwave days (any reading > 40°C)

*  Detect fully pleasant days (all readings < 30°C)



In [6]:
import numpy as np

# Create 2D array: rows = days, columns = [Morning, Afternoon, Evening]
temps = np.array([
    [25, 32, 28],  # Day 1
    [30, 35, 33],  # Day 2
    [22, 27, 25],  # Day 3
    [40, 42, 39],  # Day 4
    [29, 31, 30],  # Day 5
    [26, 28, 27],  # Day 6
    [21, 24, 23]   # Day 7
])

# Find min & max temperature of the entire week
min_temp = np.min(temps)
max_temp = np.max(temps)
print("Minimum temperature:", min_temp)
print("Maximum temperature:", max_temp)

# Average temperature of each day (axis=1 means row-wise)
daily_avg = np.mean(temps, axis=1)
print("Average temperature per day:", daily_avg)

# Heatwave Days: Any reading > 40°C
heatwave = np.any(temps > 40, axis=1)
print("Heatwave Days (True means yes):", heatwave)

# Fully Pleasant Days: All readings < 30°C
pleasant = np.all(temps < 30, axis=1)
print("Fully pleasant days (True means yes):", pleasant)

# Which days were heatwave days
heatwave_days = np.where(heatwave)[0] + 1  # +1 for human day numbering
print("Heatwave Days:", heatwave_days)


Minimum temperature: 21
Maximum temperature: 42
Average temperature per day: [28.33333333 32.66666667 24.66666667 40.33333333 30.         27.
 22.66666667]
Heatwave Days (True means yes): [False False False  True False False False]
Fully pleasant days (True means yes): [False False  True False False  True  True]
Heatwave Days: [4]






---



#  96) Hospital Health Filter
* Filter and analyze patient health records
*  Used in hospitals, diagnostic labs, or insurance to identify health risks
# Topics :

* Boolean indexing

* Conditional filtering

* np.mean, np.std, np.where()

* slicing and comparisons
# Statement:
*  You’re given data of 8 patients, and each row contains:

*  [Blood Pressure, Sugar Level, Heart Rate]

 # My tasks:

*  Find patients with high blood pressure (> 140)

*  Find patients with any abnormal value

* Find patients who are fully healthy

* Calculate average vitals

* Print report: Patient No + Result

In [15]:
import numpy as np

# Step 1: Create patient data (BP, Sugar, Heart Rate)
data = np.array([
    [120, 85, 72],
    [145, 95, 88],
    [130, 100, 70],
    [110, 90, 60],
    [160, 120, 90],
    [125, 82, 75],
    [118, 88, 77],
    [150, 140, 95]
])

# patients with high BP
high_bp = data[:, 0] > 140
print("Patients with High BP:", np.where(high_bp)[0] + 1)

#  there any abnormal value in the entire dataset
abnormal = np.any(data > [140, 110, 90])
print("Is there any abnormal value in dataset?", abnormal)

# abnormal patients (any abnormal vital in a row)
abnormal_patients = np.any(data > [140, 110, 90], axis=1)
print("Patients with any abnormal value:", np.where(abnormal_patients)[0] + 1)

# fully healthy patients (all vitals in normal range)
healthy_patients = np.all(data < [130, 100, 85], axis=1)
print("Healthy Patient Numbers:", np.where(healthy_patients)[0] + 1)

# average vitals
avg_vitals = np.mean(data, axis=0)
print("Average BP, Sugar, HR:", avg_vitals)

# Final health report
for i in range(data.shape[0]):
    status = "Healthy" if healthy_patients[i] else "Needs Attention"
    print(f"Patient {i+1}: {status}")


Patients with High BP: [2 5 8]
Is there any abnormal value in dataset? True
Patients with any abnormal value: [2 5 8]
Healthy Patient Numbers: [1 4 6 7]
Average BP, Sugar, HR: [132.25  100.     78.375]
Patient 1: Healthy
Patient 2: Needs Attention
Patient 3: Needs Attention
Patient 4: Healthy
Patient 5: Needs Attention
Patient 6: Healthy
Patient 7: Healthy
Patient 8: Needs Attention




---






# 97)Earthquake Sensor Data Analyzer
*  Used by environmental monitoring systems to detect significant earthquakes from continuous sensor readings


#Analyze
* seismic sensor data to:

* Detect dangerous spikes

*   Identify average activity levels

* Flag calm and dangerous regions

* Dataset (Simulated):

   Each row = sensor readings from a different station

   Each column = hourly seismic vibration level (0–100)

In [16]:
import numpy as np

#simulated sensor readings (rows = 5 stations, cols = 10 hourly readings)
data = np.array([
    [10, 15, 18, 21, 19, 17, 20, 19, 22, 18],
    [12, 18, 20, 45, 80, 85, 60, 50, 20, 15],
    [8,  9, 10, 12, 11, 13, 9,  10, 11, 8],
    [5,  6, 100, 110, 5, 7, 8, 6, 5, 4],
    [25, 28, 30, 35, 40, 38, 36, 42, 45, 48]
])
# Detect spikes above danger level (80+)
dangerous_spikes = data > 80
print("Danger spikes (True means dangerous):\n", dangerous_spikes)

# stations with at least 1 dangerous spike
dangerous_stations = np.any(dangerous_spikes, axis=1)
print("Stations with dangerous activity:", np.where(dangerous_stations)[0] + 1)

# average vibration per station
avg_vibration = np.mean(data, axis=1)
print("Average vibration per station:", avg_vibration)

# station with highest average
most_active = np.argmax(avg_vibration)
print("Most active station:", most_active + 1)

# 5. Calm stations (avg < 20)
calm_stations = avg_vibration < 20
print("Calm stations:", np.where(calm_stations)[0] + 1)

# 6. Final report
for i in range(data.shape[0]):
    if dangerous_stations[i]:
        status = "Dangerous"
    elif calm_stations[i]:
        status = "Calm"
    else:
        status = "Moderate"
    print(f"Station {i+1}: {status}")


Danger spikes (True means dangerous):
 [[False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [False False  True  True False False False False False False]
 [False False False False False False False False False False]]
Stations with dangerous activity: [2 4]
Average vibration per station: [17.9 40.5 10.1 25.6 36.7]
Most active station: 2
Calm stations: [1 3]
Station 1: Calm
Station 2: Dangerous
Station 3: Calm
Station 4: Dangerous
Station 5: Moderate




---



 # 98)  Sports Performance Tracker
*  Analyzing player performance across multiple games using NumPy.

*  Track and analyze scores of 4 cricket players over 5 matches using NumPy.
*   Topics:-  
reshape, transpose, stack, unique, mean, axis

In [17]:
import numpy as np

# flat list of runs (Player-wise, 4 players × 5 matches = 20 values)
runs = [45, 50, 32, 70, 66,
        80, 77, 60, 65, 75,
        20, 25, 30, 28, 35,
        55, 60, 50, 65, 70]

# convert to 2D array (4 players, 5 matches)
scores = np.array(runs).reshape(4, 5)
print("Scores (rows=players, cols=matches):\n", scores)

# transpose to get match-wise view
match_view = scores.T
print("\nScores Transposed (rows=matches, cols=players):\n", match_view)

# Step 3: Average score per player
avg_player = np.mean(scores, axis=1)
print("\nAverage score per player:", avg_player)

# Step 4: Average score per match
avg_match = np.mean(scores, axis=0)
print("Average score per match:", avg_match)

# Step 5: Stack scores with average per player (horizontal stack)
avg_player_column = avg_player.reshape(-1, 1)
full_stats = np.hstack((scores, avg_player_column))
print("\nScores + Average per player:\n", full_stats)

# Step 6: Unique scores played by all players
all_scores_flat = scores.ravel()
unique_scores = np.unique(all_scores_flat)
print("\nUnique scores in dataset:", unique_scores)

# Step 7: Final Report
for i in range(scores.shape[0]):
    print(f"Player {i+1} - Scores: {scores[i]} | Average: {avg_player[i]:.2f}")



Scores (rows=players, cols=matches):
 [[45 50 32 70 66]
 [80 77 60 65 75]
 [20 25 30 28 35]
 [55 60 50 65 70]]

Scores Transposed (rows=matches, cols=players):
 [[45 80 20 55]
 [50 77 25 60]
 [32 60 30 50]
 [70 65 28 65]
 [66 75 35 70]]

Average score per player: [52.6 71.4 27.6 60. ]
Average score per match: [50.  53.  43.  57.  61.5]

Scores + Average per player:
 [[45.  50.  32.  70.  66.  52.6]
 [80.  77.  60.  65.  75.  71.4]
 [20.  25.  30.  28.  35.  27.6]
 [55.  60.  50.  65.  70.  60. ]]

Unique scores in dataset: [20 25 28 30 32 35 45 50 55 60 65 66 70 75 77 80]
Player 1 - Scores: [45 50 32 70 66] | Average: 52.60
Player 2 - Scores: [80 77 60 65 75] | Average: 71.40
Player 3 - Scores: [20 25 30 28 35] | Average: 27.60
Player 4 - Scores: [55 60 50 65 70] | Average: 60.00




---



# 99) Weather Simulation & Forecast System
* Used by climate systems to simulate daily temperatures and analyze weather patterns


    # Simulate 7 days of temperature data for 3 cities and:

* Analyze trends

* Apply broadcasting

* Use random number generation
* Sort data




In [21]:
import numpy as np

#set seed for reproducibility
np.random.seed(42)

#simulate temperatures (3 cities × 7 days)
temps = np.random.randint(25, 45, size=(3, 7))
cities = ['Delhi', 'Mumbai', 'Chennai']
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

print("Temperature Data (°C):\n", temps)

# average temp per city
avg_city = np.mean(temps, axis=1)
print("\nAverage Temperature per City:", avg_city)

# Average temp per day
avg_day = np.mean(temps, axis=0)
print("Average Temperature per Day:", avg_day)

# Broadcasting – Convert °C to °F: F = (C × 9/5) + 32
temps_f = temps * 9/5 + 32
print("\nTemperature in Fahrenheit:\n", temps_f)

# Sort temperatures for each city (row-wise sort)
sorted_temps = np.sort(temps, axis=1)
print("\nSorted Temperatures (City-wise):\n", sorted_temps)

# hottest day per city
hottest_day_idx = np.argmax(temps, axis=1)
for i, city in enumerate(cities):
    print(f"Hottest day in {city}: {days[hottest_day_idx[i]]} ({temps[i, hottest_day_idx[i]]}°C)")

# flatten all data and get overall top 5 hottest readings
flat_all = temps.flatten()
top5 = np.sort(flat_all)[-5:]
print("\nTop 5 Hottest Readings in the Week:", top5)

Temperature Data (°C):
 [[31 44 39 35 32 31 43]
 [35 35 28 32 27 26 36]
 [30 26 25 36 36 41 34]]

Average Temperature per City: [36.42857143 31.28571429 32.57142857]
Average Temperature per Day: [32.         35.         30.66666667 34.33333333 31.66666667 32.66666667
 37.66666667]

Temperature in Fahrenheit:
 [[ 87.8 111.2 102.2  95.   89.6  87.8 109.4]
 [ 95.   95.   82.4  89.6  80.6  78.8  96.8]
 [ 86.   78.8  77.   96.8  96.8 105.8  93.2]]

Sorted Temperatures (City-wise):
 [[31 31 32 35 39 43 44]
 [26 27 28 32 35 35 36]
 [25 26 30 34 36 36 41]]
Hottest day in Delhi: Tue (44°C)
Hottest day in Mumbai: Sun (36°C)
Hottest day in Chennai: Sat (41°C)

Top 5 Hottest Readings in the Week: [36 39 41 43 44]


 # 100)Image Pixel Processor
 *  Image editing software (like Photoshop) uses NumPy to process and transform pixel data in grayscale and color images.

   #    Simulate a grayscale image and apply:

*  Reshaping & flattening

* Mathematical transformations

* Clipping values

* Transposing images

* Simulated 5×5 pixel grayscale image (values 0–255)

In [24]:
import numpy as np

# create 5×5 grayscale image with random pixel values (0-255)
np.random.seed(7)
image = np.random.randint(0, 256, size=(5, 5))
print("Original Image (5x5 pixels):\n", image)


# flatten image to 1D for storage or processing
flat_image = image.flatten()
print("\nFlattened Image:\n", flat_image)

# normalize the image (0 to 1 scale)
normalized_image = image / 255.0
print("\nNormalized Image:\n", normalized_image)

# Increase brightness by 20 units (clip values to stay within 0–255)
bright_image = np.clip(image + 20, 0, 255)
print("\nBrightened Image (+20):\n", bright_image)

# apply a mathematical function (invert image)
inverted_image = 255 - image
print("\nInverted Image (Negative Effect):\n", inverted_image)

# Transpose image (flip rows and columns)
transposed_image = image.T
print("\nTransposed Image:\n", transposed_image)

# Replace pixels < 100 with 0 (thresholding - black out dark areas)
thresholded = np.where(image < 100, 0, image)
print("\nThresholded Image (pixels < 100 = 0):\n", thresholded)


Original Image (5x5 pixels):
 [[175 196  25 246  67]
 [211 151 103  92 185]
 [142  23  72  89 110]
 [ 42 218 136 167 230]
 [ 68 176 127 135 172]]

Flattened Image:
 [175 196  25 246  67 211 151 103  92 185 142  23  72  89 110  42 218 136
 167 230  68 176 127 135 172]

Normalized Image:
 [[0.68627451 0.76862745 0.09803922 0.96470588 0.2627451 ]
 [0.82745098 0.59215686 0.40392157 0.36078431 0.7254902 ]
 [0.55686275 0.09019608 0.28235294 0.34901961 0.43137255]
 [0.16470588 0.85490196 0.53333333 0.65490196 0.90196078]
 [0.26666667 0.69019608 0.49803922 0.52941176 0.6745098 ]]

Brightened Image (+20):
 [[195 216  45 255  87]
 [231 171 123 112 205]
 [162  43  92 109 130]
 [ 62 238 156 187 250]
 [ 88 196 147 155 192]]

Inverted Image (Negative Effect):
 [[ 80  59 230   9 188]
 [ 44 104 152 163  70]
 [113 232 183 166 145]
 [213  37 119  88  25]
 [187  79 128 120  83]]

Transposed Image:
 [[175 211 142  42  68]
 [196 151  23 218 176]
 [ 25 103  72 136 127]
 [246  92  89 167 135]
 [ 67 185 110 2